name: Github CI & CD
on: push

jobs:
  eslint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: npm i
      - name: Lint Code
        run: npm run lint
